//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
#pragma pack(push, 4)
typedef struct _XML_ATTRIBUTE 
  {
    USINT *Name;  //! <Type Comment="Name of the attribute" Name="_XML_ATTRIBUTE.Name"/>
    USINT *Value;  //! <Type Comment="Value of the attribute" Name="_XML_ATTRIBUTE.Value"/>
  } _XML_ATTRIBUTE;
#pragma pack(pop)

#pragma pack(push, 4)
typedef struct _XML_ATTRIBUTE_LIST 
  {
    UDINT no;  //! <Type Comment="Number of attributes" Name="_XML_ATTRIBUTE_LIST.no"/>
    _XML_ATTRIBUTE *pList;  //! <Type Comment="Pointer at the list of attributes" Name="_XML_ATTRIBUTE_LIST.pList"/>
  } _XML_ATTRIBUTE_LIST;
#pragma pack(pop)

#pragma pack(push, 4)
typedef struct _XML_ELEMENT 
  {
    USINT *Name;  //! <Type Comment="Name of the element" Name="_XML_ELEMENT.Name"/>
    _XML_ATTRIBUTE_LIST Attributes;  //! <Type Comment="Attribute list of the element" Name="_XML_ELEMENT.Attributes"/>
    USINT *pText;  //! <Type Comment="Pointer at the text of the element" Name="_XML_ELEMENT.pText"/>
    _XML_ELEMENT *pChildren;  //! <Type Comment="Pointer at the child-elements" Name="_XML_ELEMENT.pChildren"/>
    _XML_ELEMENT *pFather;  //! <Type Comment="Pointer at the father element" Name="_XML_ELEMENT.pFather"/>
    _XML_ELEMENT *pNext;  //! <Type Comment="Pointer at the next element at the same level" Name="_XML_ELEMENT.pNext"/>
    _XML_ELEMENT *pPrevious;  //! <Type Comment="Pointer at the previous element at the same level" Name="_XML_ELEMENT.pPrevious"/>
    BOOL isClosed;  //! <Type Comment="True if element is already closed" Name="_XML_ELEMENT.isClosed"/>
  } _XML_ELEMENT;
#pragma pack(pop)

#pragma pack(push, 4)
typedef struct _XML_FILE 
  {
    USINT *Header;  //! <Type Comment="Header in the XML file" Name="_XML_FILE.Header"/>
    _XML_ELEMENT *MajorElement;  //! <Type Comment="Major and first element in the XML file" Name="_XML_FILE.MajorElement"/>
  } _XML_FILE;
#pragma pack(pop)

