//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh__MMStateSvr_PTofCls__SIG_LSL_CMultimasterState 
  {
    CHMETH *pMeth;
    _MMStateSvr dData;
    SVRDSC *pDsc;
  } SvrCh__MMStateSvr_PTofCls__SIG_LSL_CMultimasterState;

typedef struct CltCh__MMStateSvr_PTofCls__SIG_LSL_CMultimasterState 
  {
    struct SvrCh__MMStateSvr_PTofCls__SIG_LSL_CMultimasterState *pCh;
    _MMStateSvr dData;
    SVRCHCMD *pCmd;
  } CltCh__MMStateSvr_PTofCls__SIG_LSL_CMultimasterState;

typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_FeSetup 
  {
    CHMETH *pMeth;
    FeSetup dData;
    SVRDSC *pDsc;
  } SvrCh_FeSetup;

typedef struct CltCh_FeSetup 
  {
    struct SvrCh_FeSetup *pCh;
    FeSetup dData;
    SVRCHCMD *pCmd;
  } CltCh_FeSetup;

typedef struct SvrCh_HDINT 
  {
    CHMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrCh_HDINT;

typedef struct CltCh_HDINT 
  {
    struct SvrCh_HDINT *pCh;
    HDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_HDINT;

typedef struct SvrCh_IO_State 
  {
    CHMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrCh_IO_State;

typedef struct CltCh_IO_State 
  {
    struct SvrCh_IO_State *pCh;
    IO_State dData;
    SVRCHCMD *pCmd;
  } CltCh_IO_State;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__Can 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Can *pCmd;
  } CltChCmd__Can;

typedef struct CltChCmd__CanLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CanLib *pCmd;
  } CltChCmd__CanLib;

typedef struct CltChCmd__CheckSum 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CheckSum *pCmd;
  } CltChCmd__CheckSum;

typedef struct CltChCmd__FileSys 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _FileSys *pCmd;
  } CltChCmd__FileSys;

typedef struct CltChCmd__IP 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _IP *pCmd;
  } CltChCmd__IP;

typedef struct CltChCmd__Lse 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Lse *pCmd;
  } CltChCmd__Lse;

typedef struct CltChCmd__MultiTask 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _MultiTask *pCmd;
  } CltChCmd__MultiTask;

typedef struct CltChCmd__OSKernel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OSKernel *pCmd;
  } CltChCmd__OSKernel;

typedef struct CltChCmd__OsziLSEBackground 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OsziLSEBackground *pCmd;
  } CltChCmd__OsziLSEBackground;

typedef struct CltChCmd__SerLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SerLib *pCmd;
  } CltChCmd__SerLib;

typedef struct CltChCmd__StdLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _StdLib *pCmd;
  } CltChCmd__StdLib;

typedef struct CltChCmd__TaskObjectControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _TaskObjectControl *pCmd;
  } CltChCmd__TaskObjectControl;

typedef struct CltChCmd_ASCII_BIN 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ASCII_BIN *pCmd;
  } CltChCmd_ASCII_BIN;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

typedef struct CltChCmd_CriticalSection 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    CriticalSection *pCmd;
  } CltChCmd_CriticalSection;

typedef struct CltChCmd_DataManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DataManager *pCmd;
  } CltChCmd_DataManager;

typedef struct CltChCmd_DataManagerFIFO 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    DataManagerFIFO *pCmd;
  } CltChCmd_DataManagerFIFO;

typedef struct CltChCmd_DataManagerPriority 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    DataManagerPriority *pCmd;
  } CltChCmd_DataManagerPriority;

typedef struct CltChCmd_DiasMaster 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMaster *pCmd;
  } CltChCmd_DiasMaster;

typedef struct CltChCmd_DiasMasterC 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterC *pCmd;
  } CltChCmd_DiasMasterC;

typedef struct CltChCmd_DiasMasterPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterPostScan *pCmd;
  } CltChCmd_DiasMasterPostScan;

typedef struct CltChCmd_DINT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_DINT;

typedef struct CltChCmd_EEPROM 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    EEPROM *pCmd;
  } CltChCmd_EEPROM;

typedef struct CltChCmd_GetBroadCastData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetBroadCastData *pCmd;
  } CltChCmd_GetBroadCastData;

typedef struct CltChCmd_GetTaskHandle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetTaskHandle *pCmd;
  } CltChCmd_GetTaskHandle;

typedef struct CltChCmd_Graphic 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Graphic *pCmd;
  } CltChCmd_Graphic;

typedef struct CltChCmd_HmiAsciiBuffer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiAsciiBuffer *pCmd;
  } CltChCmd_HmiAsciiBuffer;

typedef struct CltChCmd_HmiCanSendReceive 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiCanSendReceive *pCmd;
  } CltChCmd_HmiCanSendReceive;

typedef struct CltChCmd_HmiChkBitList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiChkBitList *pCmd;
  } CltChCmd_HmiChkBitList;

typedef struct CltChCmd_HmiColorMap 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiColorMap *pCmd;
  } CltChCmd_HmiColorMap;

typedef struct CltChCmd_HmiComPort 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiComPort *pCmd;
  } CltChCmd_HmiComPort;

typedef struct CltChCmd_HmiFile 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiFile *pCmd;
  } CltChCmd_HmiFile;

typedef struct CltChCmd_HmiFont35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiFont35 *pCmd;
  } CltChCmd_HmiFont35;

typedef struct CltChCmd_HmiFontList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiFontList *pCmd;
  } CltChCmd_HmiFontList;

typedef struct CltChCmd_HmiFunctionList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiFunctionList *pCmd;
  } CltChCmd_HmiFunctionList;

typedef struct CltChCmd_HmiFunctionList35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiFunctionList35 *pCmd;
  } CltChCmd_HmiFunctionList35;

typedef struct CltChCmd_HmiImage35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiImage35 *pCmd;
  } CltChCmd_HmiImage35;

typedef struct CltChCmd_HmiImageList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiImageList *pCmd;
  } CltChCmd_HmiImageList;

typedef struct CltChCmd_HmiMapFile 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMapFile *pCmd;
  } CltChCmd_HmiMapFile;

typedef struct CltChCmd_HmiMemCircle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemCircle *pCmd;
  } CltChCmd_HmiMemCircle;

typedef struct CltChCmd_HmiMemImage 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemImage *pCmd;
  } CltChCmd_HmiMemImage;

typedef struct CltChCmd_HmiMemIO 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemIO *pCmd;
  } CltChCmd_HmiMemIO;

typedef struct CltChCmd_HmiMemLine 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemLine *pCmd;
  } CltChCmd_HmiMemLine;

typedef struct CltChCmd_HmiMemRectangle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemRectangle *pCmd;
  } CltChCmd_HmiMemRectangle;

typedef struct CltChCmd_HmiMemText 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemText *pCmd;
  } CltChCmd_HmiMemText;

typedef struct CltChCmd_HmiMemZorder 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemZorder *pCmd;
  } CltChCmd_HmiMemZorder;

typedef struct CltChCmd_HmiProject35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiProject35 *pCmd;
  } CltChCmd_HmiProject35;

typedef struct CltChCmd_HmiProjectList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiProjectList *pCmd;
  } CltChCmd_HmiProjectList;

typedef struct CltChCmd_HmiScreen 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiScreen *pCmd;
  } CltChCmd_HmiScreen;

typedef struct CltChCmd_HmiSetUpList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiSetUpList *pCmd;
  } CltChCmd_HmiSetUpList;

typedef struct CltChCmd_HmiSetupList35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiSetupList35 *pCmd;
  } CltChCmd_HmiSetupList35;

typedef struct CltChCmd_HmiShemeList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiShemeList *pCmd;
  } CltChCmd_HmiShemeList;

typedef struct CltChCmd_HmiShemeList35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiShemeList35 *pCmd;
  } CltChCmd_HmiShemeList35;

typedef struct CltChCmd_HmiStateBit35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiStateBit35 *pCmd;
  } CltChCmd_HmiStateBit35;

typedef struct CltChCmd_HmiStrLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiStrLib *pCmd;
  } CltChCmd_HmiStrLib;

typedef struct CltChCmd_HmiTextList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiTextList *pCmd;
  } CltChCmd_HmiTextList;

typedef struct CltChCmd_HmiTextList35 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    HmiTextList35 *pCmd;
  } CltChCmd_HmiTextList35;

typedef struct CltChCmd_HmiUniBuffer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiUniBuffer *pCmd;
  } CltChCmd_HmiUniBuffer;

typedef struct CltChCmd_HmiUnitList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiUnitList *pCmd;
  } CltChCmd_HmiUnitList;

typedef struct CltChCmd_HmiUtils 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiUtils *pCmd;
  } CltChCmd_HmiUtils;

typedef struct CltChCmd_HmiVarInfoList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiVarInfoList *pCmd;
  } CltChCmd_HmiVarInfoList;

typedef struct CltChCmd_HmiVarList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiVarList *pCmd;
  } CltChCmd_HmiVarList;

typedef struct CltChCmd_HmiVarList35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiVarList35 *pCmd;
  } CltChCmd_HmiVarList35;

typedef struct CltChCmd_Hub_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base *pCmd;
  } CltChCmd_Hub_Base;

typedef struct CltChCmd_HwControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControl *pCmd;
  } CltChCmd_HwControl;

typedef struct CltChCmd_HwControlBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControlBase *pCmd;
  } CltChCmd_HwControlBase;

typedef struct CltChCmd_HWRtPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HWRtPostScan *pCmd;
  } CltChCmd_HWRtPostScan;

typedef struct CltChCmd_I2CCDIAS 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    I2CCDIAS *pCmd;
  } CltChCmd_I2CCDIAS;

typedef struct CltChCmd_MerkerEx 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    MerkerEx *pCmd;
  } CltChCmd_MerkerEx;

typedef struct CltChCmd_Ram 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Ram *pCmd;
  } CltChCmd_Ram;

typedef struct CltChCmd_RAMex 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RAMex *pCmd;
  } CltChCmd_RAMex;

typedef struct CltChCmd_RamFile 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RamFile *pCmd;
  } CltChCmd_RamFile;

typedef struct CltChCmd_RamRingBuffer 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RamRingBuffer *pCmd;
  } CltChCmd_RamRingBuffer;

typedef struct CltChCmd_SafetyManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SafetyManager *pCmd;
  } CltChCmd_SafetyManager;

typedef struct CltChCmd_SdiasHubBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SdiasHubBase *pCmd;
  } CltChCmd_SdiasHubBase;

typedef struct SvrChCmd_t_e_VaranErrors 
  {
    CMDMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrChCmd_t_e_VaranErrors;

typedef struct CltChCmd_SdiasManager 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SdiasManager *pCmd;
  } CltChCmd_SdiasManager;

typedef struct CltChCmd_SigCLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SigCLib *pCmd;
  } CltChCmd_SigCLib;

typedef struct CltChCmd_String 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    String *pCmd;
  } CltChCmd_String;

typedef struct CltChCmd_StringInternal 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringInternal *pCmd;
  } CltChCmd_StringInternal;

typedef struct CltChCmd_StringRAM 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringRAM *pCmd;
  } CltChCmd_StringRAM;

typedef struct SvrChCmd_IO_State 
  {
    CMDMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrChCmd_IO_State;

typedef struct CltChCmd_SyncCall 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    SyncCall *pCmd;
  } CltChCmd_SyncCall;

typedef struct CltChCmd_System 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    System *pCmd;
  } CltChCmd_System;

typedef struct CltChCmd_t_e_VaranErrors 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SVRCHCMD *pCmd;
  } CltChCmd_t_e_VaranErrors;

typedef struct CltChCmd_TCPCommunication 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TCPCommunication *pCmd;
  } CltChCmd_TCPCommunication;

typedef struct CltChCmd_TCPCommunicationLogFilter 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TCPCommunicationLogFilter *pCmd;
  } CltChCmd_TCPCommunicationLogFilter;

typedef struct CltChCmd_Timer_Class 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Timer_Class *pCmd;
  } CltChCmd_Timer_Class;

typedef struct CltChCmd_Varan_Base 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Varan_Base *pCmd;
  } CltChCmd_Varan_Base;

typedef struct CltChCmd_VaranManager_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    VaranManager_Base *pCmd;
  } CltChCmd_VaranManager_Base;

typedef struct CltChCmd_WatchdogDias 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    WatchdogDias *pCmd;
  } CltChCmd_WatchdogDias;

typedef struct SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _FSM_UDP_ERROR dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP;

typedef struct SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _FSM_UDP_USER dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP;

typedef struct SvrCh__INITSTEPS_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _INITSTEPS dData;
    SVRDSC *pDsc;
  } SvrCh__INITSTEPS_PTofCls_SafetyUDP;

typedef struct SvrCh_BDINT 
  {
    CHMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrCh_BDINT;

typedef struct SvrCh_DM_CPU_Types 
  {
    CHMETH *pMeth;
    DM_CPU_Types dData;
    SVRDSC *pDsc;
  } SvrCh_DM_CPU_Types;

typedef struct SvrCh_e_GetOptions_PTofCls_NetworkConfig 
  {
    CHMETH *pMeth;
    e_GetOptions dData;
    SVRDSC *pDsc;
  } SvrCh_e_GetOptions_PTofCls_NetworkConfig;

typedef struct SvrCh_e_SetOptions_PTofCls_NetworkConfig 
  {
    CHMETH *pMeth;
    e_SetOptions dData;
    SVRDSC *pDsc;
  } SvrCh_e_SetOptions_PTofCls_NetworkConfig;

typedef struct SvrCh_SafetyConfigStateType 
  {
    CHMETH *pMeth;
    SafetyConfigStateType dData;
    SVRDSC *pDsc;
  } SvrCh_SafetyConfigStateType;

typedef struct SvrCh_SystemStateType 
  {
    CHMETH *pMeth;
    SystemStateType dData;
    SVRDSC *pDsc;
  } SvrCh_SystemStateType;

typedef struct SvrCh_t_e_ConnectionType_PTofCls_TCPCommunication 
  {
    CHMETH *pMeth;
    t_e_ConnectionType dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_ConnectionType_PTofCls_TCPCommunication;

typedef struct SvrCh_t_e_IF_NET_MODE_PTofCls__IPConfigIF 
  {
    CHMETH *pMeth;
    t_e_IF_NET_MODE dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_IF_NET_MODE_PTofCls__IPConfigIF;

typedef struct SvrCh_t_e_VaranErrors 
  {
    CHMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_VaranErrors;

typedef struct SvrCh_t_s_SamplePointState_PTofCls_AI075 
  {
    CHMETH *pMeth;
    t_s_SamplePointState dData;
    SVRDSC *pDsc;
  } SvrCh_t_s_SamplePointState_PTofCls_AI075;

typedef struct SvrCh_t_s_SdiasFWStateStandard_PTofCls_SdiasBase 
  {
    CHMETH *pMeth;
    t_s_SdiasFWStateStandard dData;
    SVRDSC *pDsc;
  } SvrCh_t_s_SdiasFWStateStandard_PTofCls_SdiasBase;

typedef struct SvrCh_t_SDIAS_Fw_State_SR_PTofCls_SR020 
  {
    CHMETH *pMeth;
    t_SDIAS_Fw_State_SR dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDIAS_Fw_State_SR_PTofCls_SR020;

typedef struct SvrCh_TErrorSvr_PTofCls_LseEasy 
  {
    CHMETH *pMeth;
    TErrorSvr dData;
    SVRDSC *pDsc;
  } SvrCh_TErrorSvr_PTofCls_LseEasy;

typedef struct SvrCh_TIME_LSL 
  {
    CHMETH *pMeth;
    TIME_LSL dData;
    SVRDSC *pDsc;
  } SvrCh_TIME_LSL;

typedef struct SvrCh_TStateSvr_PTofCls_LseEasy 
  {
    CHMETH *pMeth;
    TStateSvr dData;
    SVRDSC *pDsc;
  } SvrCh_TStateSvr_PTofCls_LseEasy;

typedef struct SvrChCmd_BDINT 
  {
    CMDMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_BDINT;

typedef struct SvrChCmd_DATE_LSL 
  {
    CMDMETH *pMeth;
    DATE_LSL dData;
    SVRDSC *pDsc;
  } SvrChCmd_DATE_LSL;

typedef struct SvrChCmd_iprStates 
  {
    CMDMETH *pMeth;
    iprStates dData;
    SVRDSC *pDsc;
  } SvrChCmd_iprStates;

